/**
 * Comprehensive Question Bank for SkillSetu Diagnostic & Assessment Engine
 * Parts:
 * (a) Domain-Specific Technical MCQs (Engineering, Management, Healthcare/Ayush, Commerce/Finance, Science, Design)
 * (b) Domain-Agnostic Aptitude (Logical Reasoning, Quantitative, Verbal)
 * (c) Soft-Skill Behavioral & Scenario Rating Questions
 */

export const APTITUDE_QUESTIONS = [
  {
    id: 'apt_01',
    category: 'Aptitude - Logical Reasoning',
    question: 'In a certain code, "BRIDGE" is written as "CQKGFD". How would "TUNNEL" be written in that code?',
    options: ['UVPODM', 'UWPODK', 'UVPODK', 'TVPODM'],
    correctAnswer: 'UVPODK',
    explanation: 'Pattern involves shifting alternating consonants (+1, +2, -1, etc.).',
  },
  {
    id: 'apt_02',
    category: 'Aptitude - Logical Reasoning',
    question: 'Statement: "All engineers understand math. Some designers are engineers." Which conclusion definitely follows?',
    options: [
      'All designers understand math.',
      'Some designers understand math.',
      'No designer understands math.',
      'All mathematicians are designers.',
    ],
    correctAnswer: 'Some designers understand math.',
    explanation: 'The subset of designers that are engineers necessarily understands math.',
  },
  {
    id: 'apt_03',
    category: 'Aptitude - Quantitative',
    question: 'A project team delivers 3 modules in 12 days working 6 hours a day. How many hours a day must they work to finish 5 modules in 15 days?',
    options: ['6.5 hours', '8.0 hours', '7.2 hours', '9.0 hours'],
    correctAnswer: '8.0 hours',
    explanation: '(M1 * D1 * H1) / W1 = (M2 * D2 * H2) / W2 => (1 * 12 * 6)/3 = (1 * 15 * H2)/5 => 24 = 3 * H2 => H2 = 8.',
  },
  {
    id: 'apt_04',
    category: 'Aptitude - Quantitative',
    question: 'An enterprise investment yields a 20% profit in Year 1 and suffers a 10% depreciation in Year 2. What is the net percentage return?',
    options: ['+10%', '+8%', '+12%', '+5%'],
    correctAnswer: '+8%',
    explanation: 'Effective multiplier: 1.20 * 0.90 = 1.08, which represents an 8% net gain.',
  },
  {
    id: 'apt_05',
    category: 'Aptitude - Verbal Ability',
    question: 'Choose the word closest in meaning to "PRAGMATIC":',
    options: ['Theoretical', 'Practical and realistic', 'Dogmatic', 'Impulsive'],
    correctAnswer: 'Practical and realistic',
    explanation: '"Pragmatic" refers to dealing with things sensibly and realistically based on practical rather than theoretical considerations.',
  },
  {
    id: 'apt_06',
    category: 'Aptitude - Verbal Ability',
    question: 'Identify the grammatically most accurate sentence for a technical proposal:',
    options: [
      'Neither the project lead nor the research analysts was present.',
      'Neither the project lead nor the research analysts were present.',
      'Neither the project lead or the research analysts were present.',
      'Neither the project lead nor the research analysts has been present.',
    ],
    correctAnswer: 'Neither the project lead nor the research analysts were present.',
    explanation: 'With "neither... nor", the verb agrees with the closer subject ("research analysts" -> plural "were").',
  },
];

export const SOFT_SKILLS_QUESTIONS = [
  {
    id: 'soft_01',
    category: 'Soft Skills - Conflict Resolution & Teamwork',
    question: 'During a cross-functional milestone, your technical partner strongly opposes your proposed design architecture 48 hours before the prototype deadline. What is your optimal action?',
    options: [
      'Escalate immediately to the departmental dean or project director without further discussion.',
      'Convene a 30-minute objective evaluation matrix comparing trade-offs, fallback risks, and user impact to find consensus.',
      'Concede completely to avoid any friction and meet the immediate deadline.',
      'Silently build your own version in parallel and submit both simultaneously.',
    ],
    correctAnswer: 'Convene a 30-minute objective evaluation matrix comparing trade-offs, fallback risks, and user impact to find consensus.',
  },
  {
    id: 'soft_02',
    category: 'Soft Skills - Ownership & Leadership',
    question: 'You identify an unexpected data calculation error in a report that was already dispatched to an industry client. What represents highest professional accountability?',
    options: [
      'Wait for the client to notice first before acknowledging the issue.',
      'Immediately alert your project lead with a rectified report, clear impact delta, and proactive mitigation steps.',
      'Blame the automated data extraction pipeline and request an external audit.',
      'Discreetly replace the server file without alerting any stakeholders.',
    ],
    correctAnswer: 'Immediately alert your project lead with a rectified report, clear impact delta, and proactive mitigation steps.',
  },
  {
    id: 'soft_03',
    category: 'Soft Skills - Adaptability & Time Management',
    question: 'Three high-priority deliverables with identical deadlines are assigned to you by two different department managers. How do you prioritize effectively?',
    options: [
      'Work randomly on whichever assignment is easiest to finish first.',
      'Estimate effort, map dependencies, and schedule a 10-minute tripartite alignment to establish a clear sequential priority order.',
      'Ignore one manager completely and prioritize the other.',
      'Work 24 hours continuously without communicating constraints.',
    ],
    correctAnswer: 'Estimate effort, map dependencies, and schedule a 10-minute tripartite alignment to establish a clear sequential priority order.',
  },
  {
    id: 'soft_04',
    category: 'Soft Skills - Critical Thinking',
    question: 'A pilot clinical or engineering dataset demonstrates a 99% correlation between two unrelated variables. What is the scientifically rigorous approach?',
    options: [
      'Accept immediate causation and publish the breakthrough finding.',
      'Investigate potential confounding variables, sample selection bias, and check whether correlation is spurious.',
      'Discard the entire dataset as corrupt.',
      'Selectively omit outliers until the correlation aligns with conventional expectations.',
    ],
    correctAnswer: 'Investigate potential confounding variables, sample selection bias, and check whether correlation is spurious.',
  },
];

export const TECHNICAL_QUESTIONS_BY_DOMAIN = {
  'Engineering & Technology': [
    {
      id: 'eng_01',
      subField: 'Computer Science & IT',
      skill: 'DSA',
      question: 'What is the worst-case time complexity of searching in a balanced Binary Search Tree (e.g., AVL or Red-Black)?',
      options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
      correctAnswer: 'O(log n)',
      explanation: 'Balanced BSTs maintain height bounded by log n, ensuring worst-case search is O(log n).',
    },
    {
      id: 'eng_02',
      subField: 'Computer Science & IT',
      skill: 'React',
      question: 'In React 18+, which hook is specifically designed to memoize heavy computational functions across re-renders without re-executing unless dependencies change?',
      options: ['useEffect', 'useMemo', 'useCallback', 'useRef'],
      correctAnswer: 'useMemo',
      explanation: 'useMemo caches the result of a calculation between renders.',
    },
    {
      id: 'eng_03',
      subField: 'Computer Science & IT',
      skill: 'Node.js',
      question: 'In Node.js event loop architecture, in which phase are `setImmediate()` callbacks executed?',
      options: ['Timers phase', 'Poll phase', 'Check phase', 'Close callbacks phase'],
      correctAnswer: 'Check phase',
      explanation: '`setImmediate` callbacks are executed in the Check phase immediately after I/O polling.',
    },
    {
      id: 'eng_04',
      subField: 'Computer Science & IT',
      skill: 'System Design',
      question: 'Which consistency model ensures that every read receives the most recent write or an error in a distributed system under CAP theorem?',
      options: ['Eventual Consistency', 'Strong Consistency (Linearizability)', 'Causal Consistency', 'Monotonic Read Consistency'],
      correctAnswer: 'Strong Consistency (Linearizability)',
      explanation: 'Strong consistency guarantees immediate visibility of all committed writes across all nodes.',
    },
    {
      id: 'eng_05',
      subField: 'Data Science & AI',
      skill: 'Machine Learning',
      question: 'When an ML model exhibits high variance (overfitting), which regularization technique adds an L2 penalty proportional to the square of coefficient magnitudes?',
      options: ['Lasso Regression', 'Ridge Regression', 'Elastic Net', 'Decision Tree Pruning'],
      correctAnswer: 'Ridge Regression',
      explanation: 'Ridge uses an L2 penalty (sum of squared weights), shrinking weights towards zero.',
    },
    {
      id: 'eng_06',
      subField: 'Data Science & AI',
      skill: 'Deep Learning',
      question: 'In Transformer neural networks, what mechanism allows tokens to attend to different positions within the same sequence simultaneously?',
      options: ['Recurrent Feedback Loop', 'Multi-Head Self-Attention', 'Convolutional Pooling', 'Gated Recurrent Unit'],
      correctAnswer: 'Multi-Head Self-Attention',
      explanation: 'Multi-head attention projects queries, keys, and values into multiple representation subspaces.',
    },
    {
      id: 'eng_07',
      subField: 'Electronics & Communication',
      skill: 'Embedded C',
      question: 'Why is the `volatile` keyword utilized when declaring memory-mapped hardware peripheral registers in Embedded C?',
      options: [
        'To instruct the compiler to allocate the variable in CPU cache memory.',
        'To prevent the compiler from optimizing away reads/writes whose values may change asynchronously.',
        'To make the variable read-only across all functions.',
        'To automatically synchronize mutex locks across threads.',
      ],
      correctAnswer: 'To prevent the compiler from optimizing away reads/writes whose values may change asynchronously.',
    },
    {
      id: 'eng_08',
      subField: 'Electronics & Communication',
      skill: 'IoT Protocols',
      question: 'Which lightweight publish-subscribe protocol operates over TCP with minimal packet headers, ideal for constrained IoT telemetry?',
      options: ['HTTP/2', 'MQTT', 'FTP', 'Telnet'],
      correctAnswer: 'MQTT',
      explanation: 'MQTT uses a 2-byte fixed header and binary payload, making it ultra-efficient for low-bandwidth networks.',
    },
    {
      id: 'eng_09',
      subField: 'Mechanical & Automation',
      skill: 'CAD/SolidWorks',
      question: 'In parametric CAD modeling, what type of geometric constraint forces two circular arc centers to coincide exactly?',
      options: ['Tangent constraint', 'Concentric constraint', 'Collinear constraint', 'Parallel constraint'],
      correctAnswer: 'Concentric constraint',
      explanation: 'Concentric constraints lock the centers of two or more circular entities together.',
    },
    {
      id: 'eng_10',
      subField: 'Mechanical & Automation',
      skill: 'PLC/SCADA',
      question: 'In industrial PLC programming (IEC 61131-3), which graphical language models control logic analogous to electrical relay schematics?',
      options: ['Structured Text (ST)', 'Ladder Diagram (LD)', 'Instruction List (IL)', 'Sequential Function Chart (SFC)'],
      correctAnswer: 'Ladder Diagram (LD)',
      explanation: 'Ladder Diagram mimics the appearance of electrical relay ladder logic diagrams.',
    },
    {
      id: 'eng_11',
      subField: 'Civil & Infrastructure',
      skill: 'STAAD Pro',
      question: 'In structural engineering design, what is the primary purpose of performing a P-Delta analysis on multi-story frames?',
      options: [
        'To evaluate second-order geometric non-linear effects caused by axial loads acting on deflected lateral structures.',
        'To test thermal conductivity of concrete slabs.',
        'To calculate paint surface area for bill of quantities.',
        'To model soil liquefaction velocity exclusively.',
      ],
      correctAnswer: 'To evaluate second-order geometric non-linear effects caused by axial loads acting on deflected lateral structures.',
    },
    {
      id: 'eng_12',
      subField: 'Biotechnology & Bio-Engineering',
      skill: 'HPLC',
      question: 'In Reversed-Phase High-Performance Liquid Chromatography (RP-HPLC), what is the typical polarity of the stationary phase relative to the mobile phase?',
      options: [
        'Stationary phase is non-polar (hydrophobic, e.g. C18) while mobile phase is polar.',
        'Stationary phase is highly polar silica while mobile phase is non-polar hexane.',
        'Both stationary and mobile phases must be strictly non-polar.',
        'The mobile phase is solid while the stationary phase is gaseous.',
      ],
      correctAnswer: 'Stationary phase is non-polar (hydrophobic, e.g. C18) while mobile phase is polar.',
    },
    {
      id: 'eng_13',
      subField: 'Computer Science & IT',
      skill: 'Cloud/AWS',
      question: 'Which AWS service provides serverless event-driven compute without provisioning or managing virtual machines?',
      options: ['Amazon EC2', 'AWS Lambda', 'Amazon RDS', 'Amazon EBS'],
      correctAnswer: 'AWS Lambda',
      explanation: 'AWS Lambda executes code in response to events and automatically scales compute capacity.',
    },
    {
      id: 'eng_14',
      subField: 'Computer Science & IT',
      skill: 'Docker',
      question: 'What is the primary operational advantage of multi-stage Docker builds?',
      options: [
        'They generate dramatically smaller, hardened production container images by separating compilation tooling from runtime artifacts.',
        'They execute containers without Linux kernel cgroups.',
        'They bypass network firewall restrictions.',
        'They compress git history into tarballs.',
      ],
      correctAnswer: 'They generate dramatically smaller, hardened production container images by separating compilation tooling from runtime artifacts.',
    },
    {
      id: 'eng_15',
      subField: 'Data Science & AI',
      skill: 'SQL',
      question: 'Which SQL window function assigns a unique sequential integer to rows within a partition based on a specified ordering without gaps?',
      options: ['RANK()', 'DENSE_RANK()', 'ROW_NUMBER()', 'LEAD()'],
      correctAnswer: 'ROW_NUMBER()',
      explanation: 'ROW_NUMBER() guarantees unique incremental integers (1, 2, 3...) regardless of tied values.',
    },
  ],

  'Management & Business': [
    {
      id: 'mgt_01',
      subField: 'Finance & Corporate Strategy',
      skill: 'Financial Modeling',
      question: 'In a Discounted Cash Flow (DCF) valuation, what does the Weighted Average Cost of Capital (WACC) represent?',
      options: [
        'The overall blended hurdle rate or required rate of return that a firm must earn on its existing asset base to satisfy all capital providers.',
        'The interest rate charged by central banks on short-term loans.',
        'The pure dividend yield paid on preference shares.',
        'The historical average accounting tax rate.',
      ],
      correctAnswer: 'The overall blended hurdle rate or required rate of return that a firm must earn on its existing asset base to satisfy all capital providers.',
    },
    {
      id: 'mgt_02',
      subField: 'Marketing & Growth',
      skill: 'Digital Marketing & SEO',
      question: 'In digital acquisition, if a campaign spends ₹50,000 to generate 250 paying customers, what is the Customer Acquisition Cost (CAC)?',
      options: ['₹100', '₹200', '₹500', '₹1,250'],
      correctAnswer: '₹200',
      explanation: 'CAC = Total Acquisition Spend / New Customers Acquired = 50,000 / 250 = ₹200.',
    },
    {
      id: 'mgt_03',
      subField: 'Operations & Supply Chain',
      skill: 'Six Sigma / Lean',
      question: 'In Lean manufacturing methodology, which term describes "unnecessary waiting or inventory waste" that adds zero value to the customer?',
      options: ['Kaizen', 'Muda', 'Poka-Yoke', 'Kanban'],
      correctAnswer: 'Muda',
      explanation: '"Muda" is the Japanese term for wastefulness or uselessness.',
    },
    {
      id: 'mgt_04',
      subField: 'Product Management',
      skill: 'Product Lifecycle Management',
      question: 'What is the primary function of an ICE (Impact, Confidence, Ease) scoring matrix in product prioritization?',
      options: [
        'To objectively quantify and rank user stories and feature hypotheses against engineering constraints.',
        'To calculate employee payroll deductions.',
        'To verify server latency metrics.',
        'To manage legal intellectual property filings.',
      ],
      correctAnswer: 'To objectively quantify and rank user stories and feature hypotheses against engineering constraints.',
    },
    {
      id: 'mgt_05',
      subField: 'Human Resources & Talent Management',
      skill: 'Talent Acquisition',
      question: 'What does "Quality of Hire" in contemporary talent acquisition analytics primarily assess?',
      options: [
        'The number of resumes reviewed per day by a recruiter.',
        'The candidate retention rate, time to full productivity, and performance appraisal ratings post-onboarding.',
        'The font style selected for job descriptions.',
        'The total cost of office coffee machines.',
      ],
      correctAnswer: 'The candidate retention rate, time to full productivity, and performance appraisal ratings post-onboarding.',
    },
    {
      id: 'mgt_06',
      subField: 'Finance & Corporate Strategy',
      skill: 'Valuation (DCF)',
      question: 'When Free Cash Flow to Firm (FCFF) is discounted to calculate enterprise value, which cash flows are included?',
      options: [
        'Cash flow available to all suppliers of capital after operating expenses, taxes, working capital investment, and capital expenditures.',
        'Only net profit after dividend disbursements.',
        'Gross revenue before deducting cost of goods sold.',
        'Retained earnings from previous fiscal decades.',
      ],
      correctAnswer: 'Cash flow available to all suppliers of capital after operating expenses, taxes, working capital investment, and capital expenditures.',
    },
    {
      id: 'mgt_07',
      subField: 'Operations & Supply Chain',
      skill: 'Supply Chain Optimization',
      question: 'What is the "Bullwhip Effect" in supply chain management?',
      options: [
        'The phenomenon where slight fluctuations in consumer retail demand trigger progressively amplified inventory swings upstream along the supply chain.',
        'A sudden drop in sea freight shipping container prices.',
        'Labor union strikes at central ports.',
        'Rapid physical deterioration of perishable crops.',
      ],
      correctAnswer: 'The phenomenon where slight fluctuations in consumer retail demand trigger progressively amplified inventory swings upstream along the supply chain.',
    },
    {
      id: 'mgt_08',
      subField: 'Marketing & Growth',
      skill: 'Brand Strategy',
      question: 'In marketing strategy, what is a "Unique Value Proposition" (UVP)?',
      options: [
        'A clear statement describing the specific benefit of an offering, how it solves customer pain points, and why it is superior to alternatives.',
        'The government trademark registration certificate number.',
        'The wholesale discount rate provided to distributors.',
        'A social media influencer disclaimer.',
      ],
      correctAnswer: 'A clear statement describing the specific benefit of an offering, how it solves customer pain points, and why it is superior to alternatives.',
    },
    {
      id: 'mgt_09',
      subField: 'Product Management',
      skill: 'Agile/Scrum',
      question: 'In Scrum sprint planning, who possesses final authority over the prioritization of items in the Product Backlog?',
      options: ['The Scrum Master', 'The Product Owner', 'The Lead Architect', 'The External Client'],
      correctAnswer: 'The Product Owner',
      explanation: 'The Product Owner is solely accountable for maximizing value and ordering the Product Backlog.',
    },
    {
      id: 'mgt_10',
      subField: 'Finance & Corporate Strategy',
      skill: 'Advanced Excel',
      question: 'Which modern Excel formula dynamically looks up values to the left or right without being constrained by table column order?',
      options: ['VLOOKUP', 'HLOOKUP', 'XLOOKUP', 'MATCH alone'],
      correctAnswer: 'XLOOKUP',
      explanation: 'XLOOKUP replaces both VLOOKUP and HLOOKUP with flexible bidirectional searching.',
    },
  ],

  'Healthcare & Ayush': [
    {
      id: 'hlt_01',
      subField: 'Ayurveda & Traditional Medicine',
      skill: 'Classical Diagnostic Principles (Ashtavidha)',
      question: 'In classical Ayurvedic clinical examination (Ashtavidha Pariksha), which parameter assesses cardiovascular and metabolic vitality via arterial palpation?',
      options: ['Nadi Pariksha (Pulse examination)', 'Mutra Pariksha (Urine)', 'Mala Pariksha (Stool)', 'Jihwa Pariksha (Tongue)'],
      correctAnswer: 'Nadi Pariksha (Pulse examination)',
      explanation: 'Nadi Pariksha provides direct tactile insight into Tridosha dynamics and systemic balance.',
    },
    {
      id: 'hlt_02',
      subField: 'Ayurveda & Traditional Medicine',
      skill: 'Panchakarma Protocol Design',
      question: 'Before administering Vamana or Virechana therapeutic purification, which preparatory procedure (Purvakarma) softens toxins through internal/external oleation?',
      options: ['Snehana', 'Swedana', 'Nasya', 'Shirodhara'],
      correctAnswer: 'Snehana',
      explanation: 'Snehana (oleation therapy) mobilizes deep-seated toxins prior to Swedana and Shodhana.',
    },
    {
      id: 'hlt_03',
      subField: 'Pharmaceutical Sciences & Regulatory',
      skill: 'Good Manufacturing Practices (GMP)',
      question: 'Under Schedule T of the Drugs and Cosmetics Act (India), what is mandatory for manufacturing Ayurvedic and herbal formulations?',
      options: [
        'Good Manufacturing Practices (GMP) certification ensuring hygiene, standardized equipment, and batch testing laboratories.',
        'Exclusive use of open-air sun drying without climate controls.',
        'Selling solely through registered clinics without batch numbers.',
        'Exemption from shelf-life stability testing.',
      ],
      correctAnswer: 'Good Manufacturing Practices (GMP) certification ensuring hygiene, standardized equipment, and batch testing laboratories.',
    },
    {
      id: 'hlt_04',
      subField: 'Clinical Research & Trials',
      skill: 'Good Clinical Practice (GCP)',
      question: 'In an ICH-GCP compliant clinical research protocol, what is the primary role of an Institutional Ethics Committee (IEC)?',
      options: [
        'To maximize clinical trial profits for the sponsor pharmaceutical corporation.',
        'To safeguard the rights, safety, and well-being of trial human participants and approve informed consent documents.',
        'To expedite commercial marketing approvals without trial completion.',
        'To hire medical representatives for field sales.',
      ],
      correctAnswer: 'To safeguard the rights, safety, and well-being of trial human participants and approve informed consent documents.',
    },
    {
      id: 'hlt_05',
      subField: 'Health Informatics & Digital Health',
      skill: 'Ayushman Bharat Digital Mission (ABDM) Standards',
      question: 'In India’s ABDM digital health ecosystem, what is an Ayushman Bharat Health Account (ABHA)?',
      options: [
        'A 14-digit unique identifier allowing citizens to securely aggregate, share, and access digital health records with consent across providers.',
        'A commercial cryptocurrency token for hospital billing.',
        'An international visa document for medical tourism.',
        'A physical hospital smartcard exclusively usable at single dispensaries.',
      ],
      correctAnswer: 'A 14-digit unique identifier allowing citizens to securely aggregate, share, and access digital health records with consent across providers.',
    },
    {
      id: 'hlt_06',
      subField: 'Ayurveda & Traditional Medicine',
      skill: 'Dravyaguna & Herbal Identification',
      question: 'Which active phyto-constituent standardizes classical Ashwagandha (Withania somnifera) root extract for pharmacological potency?',
      options: ['Withanolides (e.g. Withaferin A)', 'Curcuminoids', 'Piperine', 'Guggulsterones'],
      correctAnswer: 'Withanolides (e.g. Withaferin A)',
      explanation: 'Withanolides are steroidal lactones responsible for the adaptogenic and neuroprotective efficacy of Ashwagandha.',
    },
    {
      id: 'hlt_07',
      subField: 'Clinical Research & Trials',
      skill: 'Pharmacovigilance Reporting',
      question: 'In Ayush pharmacovigilance (Ayush Suraksha), what constitutes a Serious Adverse Event (SAE)?',
      options: [
        'Any untoward medical occurrence resulting in death, inpatient hospitalization, persistent disability, or congenital anomaly.',
        'A minor temporary headache relieved by hydration.',
        'A patient requesting a change of appointment time.',
        'Mild disflavor of an herbal decoction.',
      ],
      correctAnswer: 'Any untoward medical occurrence resulting in death, inpatient hospitalization, persistent disability, or congenital anomaly.',
    },
  ],

  'Commerce & Finance': [
    {
      id: 'com_01',
      subField: 'Accounting & Audit',
      skill: 'GST Filing & Compliance',
      question: 'Under Indian GST legislation, which return forms the monthly consolidated summary of outward and inward supplies and tax liabilities?',
      options: ['GSTR-3B', 'GSTR-1', 'GSTR-9', 'GSTR-4'],
      correctAnswer: 'GSTR-3B',
      explanation: 'GSTR-3B is the monthly self-declared summary return for tax payment and ITC utilization.',
    },
    {
      id: 'com_02',
      subField: 'Banking & Fintech',
      skill: 'Fintech APIs & Payments',
      question: 'In UPI (Unified Payments Interface) architecture, what role does NPCI (National Payments Corporation of India) perform?',
      options: [
        'Central real-time settlement switch and interoperability gateway routing between remitter and beneficiary banks.',
        'Physical retail bank maintaining individual savings deposits.',
        'Foreign exchange regulator approving cross-border hedge funds.',
        'Sole equity underwriter for IPO listings.',
      ],
      correctAnswer: 'Central real-time settlement switch and interoperability gateway routing between remitter and beneficiary banks.',
    },
    {
      id: 'com_03',
      subField: 'Accounting & Audit',
      skill: 'Ind AS / IFRS',
      question: 'Under Ind AS 115 / IFRS 15, what is the core 5-step principle for recognizing revenue from contracts with customers?',
      options: [
        'Identify contract -> Identify performance obligations -> Determine transaction price -> Allocate price -> Recognize revenue when obligations are satisfied.',
        'Record revenue whenever physical cash arrives at the counter.',
        'Recognize all annual revenue on January 1st regardless of shipment.',
        'Defer all income indefinitely until tax audits complete.',
      ],
      correctAnswer: 'Identify contract -> Identify performance obligations -> Determine transaction price -> Allocate price -> Recognize revenue when obligations are satisfied.',
    },
  ],

  'Design & Creative Arts': [
    {
      id: 'dsg_01',
      subField: 'UI/UX & Product Design',
      skill: 'Design Systems',
      question: 'In atomic design methodology (Brad Frost), what layer consists of distinct combinations of atoms functioning together as a reusable unit (e.g. search form)?',
      options: ['Molecules', 'Organisms', 'Templates', 'Pages'],
      correctAnswer: 'Molecules',
      explanation: 'Molecules are simple groups of UI elements (atoms) bonded together to do one job.',
    },
    {
      id: 'dsg_02',
      subField: 'UI/UX & Product Design',
      skill: 'Figma',
      question: 'In Figma, what feature enables responsive card containers to expand or wrap dynamically according to their child content padding and gaps?',
      options: ['Auto Layout', 'Component Variants', 'Boolean Groups', 'Smart Animate'],
      correctAnswer: 'Auto Layout',
      explanation: 'Auto Layout adds flexbox-like dynamic spacing, padding, and alignment properties.',
    },
  ],

  'Science & Research': [
    {
      id: 'sci_01',
      subField: 'Applied Chemistry & Material Science',
      skill: 'Spectroscopy (NMR/IR/UV)',
      question: 'In Infrared (IR) spectroscopy, which diagnostic wavenumber range typically characterizes a strong Carbonyl (C=O) stretching absorption band?',
      options: ['1680 - 1750 cm⁻¹', '3200 - 3600 cm⁻¹', '600 - 800 cm⁻¹', '2100 - 2260 cm⁻¹'],
      correctAnswer: '1680 - 1750 cm⁻¹',
      explanation: 'Carbonyl bonds exhibit intense characteristic stretches around ~1700 cm⁻¹.',
    },
    {
      id: 'sci_02',
      subField: 'Environmental Science & Sustainability',
      skill: 'Carbon Accounting & ESG',
      question: 'Under the GHG Protocol Corporate Standard, what do Scope 2 emissions encompass?',
      options: [
        'Indirect GHG emissions from the generation of purchased electricity, steam, heating, or cooling consumed by the reporting organization.',
        'Direct emissions from company-owned factory furnaces and vehicles.',
        'Upstream employee commuting and raw material freight.',
        'End-of-life disposal of sold customer goods.',
      ],
      correctAnswer: 'Indirect GHG emissions from the generation of purchased electricity, steam, heating, or cooling consumed by the reporting organization.',
    },
  ],
};
