/**
 * Seed dataset for SkillSetu - All-Domain Taxonomy Edition
 * Balanced distribution:
 * - 40% Engineering & Technology
 * - 20% Management & Business
 * - 10% Healthcare & Ayush
 * - 30% across Design, Science & Research, Commerce & Finance, Agriculture
 */

export const SHARED_DEMO_PASSWORD = 'Password@123';

export const seedInstitutions = [
  {
    name: 'National Institute of Technology & Allied Health Sciences',
    code: 'NIT-AHS-001',
    type: 'Premier Autonomous University',
    location: { city: 'New Delhi', state: 'Delhi', country: 'India' },
    approvalStatus: 'approved',
    placementCell: {
      headName: 'Dr. Rameshwar V. Sharma',
      email: 'placement@institution.edu.in',
      phone: '+91-11-26950401',
    },
    website: 'https://skillsetu.edu.in',
    moUsSigned: 38,
  },
];

export const demoAccounts = [
  {
    name: 'Aarav Sharma (Demo Student)',
    email: 'demo.student@skillsetu.in',
    role: 'student',
    primaryDomain: 'Engineering & Technology',
    subField: 'Computer Science & IT',
    secondaryDomains: ['Data Science & AI', 'UI/UX & Product Design'],
    degree: 'B.Tech Computer Science & Engineering',
    course: 'B.Tech',
    year: 3,
    semester: 6,
    skills: ['React', 'Node.js', 'Python', 'SQL', 'Git', 'Data Structures', 'Docker'],
    interests: ['Full Stack Development', 'Cloud Architecture', 'Health Informatics', 'AI Systems'],
    profile: {
      title: 'Pre-Final Year Engineering Scholar & Full-Stack Apprentice',
      degree: 'B.Tech in Computer Science and Engineering',
      department: 'School of Computing & Information Technology',
      batch: '2022-2026',
      cgpa: 8.85,
      location: 'New Delhi, India',
      targetRole: 'Full-Stack Software Engineer',
    },
  },
  {
    name: 'Prof. (Dr.) Manisha Kulkarni (Demo Faculty)',
    email: 'demo.faculty@skillsetu.in',
    role: 'academician',
    primaryDomain: 'Healthcare & Ayush',
    subField: 'Ayurveda & Traditional Medicine',
    skills: ['Clinical Research', 'Panchakarma Protocol Design', 'Curriculum Design', 'Phyto-Pharmaceutical Analysis'],
    interests: ['Integrative Medicine', 'Herbal Standardization', 'Industry-Academia MoUs'],
    profile: {
      title: 'Professor & Head of Research Alliances',
      designation: 'Senior Professor & Clinical Research Lead',
      department: 'Department of Clinical Research & Integrative Therapeutics',
      researchAreas: ['Evidence-Based Therapeutics', 'Neuro-degenerative Protocol Studies', 'Digital Health Diagnostics'],
      publicationsCount: 42,
      location: 'New Delhi, India',
    },
  },
  {
    name: 'Vikramaditya Singhania (Demo Recruiter)',
    email: 'demo.industry@skillsetu.in',
    role: 'industry',
    primaryDomain: 'Engineering & Technology',
    subField: 'Computer Science & IT',
    skills: ['Talent Acquisition', 'Engineering Leadership', 'Campus Hiring', 'Agile Product Strategy'],
    interests: ['High-Performance Distributed Systems', 'AI Innovation', 'University Hackathons'],
    profile: {
      title: 'Director of Talent Alliances & Campus Programs',
      companyName: 'NexGen Technologies & Cloud Solutions',
      companyWebsite: 'https://nexgen.tech.example.com',
      industrySector: 'Information Technology & Cloud Infrastructure',
      companySize: '1,000 - 5,000 employees',
      location: 'Bengaluru & Gurgaon, India',
    },
  },
  {
    name: 'Dr. Anandvardhan Pathak (Demo Admin)',
    email: 'demo.institution@skillsetu.in',
    role: 'institution',
    skills: ['Institutional Governance', 'Smart Automation Oversight', 'NAAC/NABH Accreditation', 'Placement Strategy'],
    interests: ['Industry Collaboration Frameworks', 'Skill Gap Analytics', 'Ayush & Tech Start-up Incubation'],
    profile: {
      title: 'Dean of Academic Collaborations & Placement Cell Director',
      officialDesignation: 'Director of University Alliances',
      department: 'Academic & Industry Interface Cell',
      location: 'National Campus, New Delhi',
    },
  },
];

export const additionalStudents = [
  // 40% Engineering
  {
    name: 'Rohan Deshmukh',
    email: 'rohan.deshmukh@student.in',
    role: 'student',
    primaryDomain: 'Engineering & Technology',
    subField: 'Data Science & AI',
    degree: 'B.Tech Data Science',
    year: 4,
    semester: 7,
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'SQL', 'NLP'],
    interests: ['Predictive Modeling', 'Deep Learning'],
    profile: { degree: 'B.Tech Data Science', department: 'Computer Science', cgpa: 9.1, batch: '2021-2025' },
  },
  {
    name: 'Sneha Venkatesh',
    email: 'sneha.v@student.in',
    role: 'student',
    primaryDomain: 'Engineering & Technology',
    subField: 'Electronics & Communication',
    degree: 'B.Tech ECE',
    year: 3,
    semester: 5,
    skills: ['Embedded C', 'IoT Protocols', 'MATLAB', 'VLSI Design'],
    interests: ['Edge Computing', 'Automotive Electronics'],
    profile: { degree: 'B.Tech ECE', department: 'ECE', cgpa: 8.4, batch: '2022-2026' },
  },
  {
    name: 'Kavita Menon',
    email: 'kavita.menon@student.in',
    role: 'student',
    primaryDomain: 'Engineering & Technology',
    subField: 'Mechanical & Automation',
    degree: 'B.Tech Mechanical Engineering',
    year: 4,
    semester: 8,
    skills: ['CAD/SolidWorks', 'ANSYS', 'Robotics/ROS', 'PLC/SCADA'],
    interests: ['Electric Vehicles', 'Additive Manufacturing'],
    profile: { degree: 'B.Tech Mechanical', department: 'Mechanical', cgpa: 8.7, batch: '2021-2025' },
  },
  {
    name: 'Aditya Srivastava',
    email: 'aditya.s@student.in',
    role: 'student',
    primaryDomain: 'Engineering & Technology',
    subField: 'Computer Science & IT',
    degree: 'B.Tech CSE',
    year: 2,
    semester: 4,
    skills: ['Java', 'Spring Boot', 'DSA', 'PostgreSQL', 'Docker'],
    interests: ['Backend Systems', 'Microservices'],
    profile: { degree: 'B.Tech CSE', department: 'CSE', cgpa: 8.6, batch: '2023-2027' },
  },
  // 20% Management
  {
    name: 'Ananya Roy',
    email: 'ananya.roy@student.in',
    role: 'student',
    primaryDomain: 'Management & Business',
    subField: 'Finance & Corporate Strategy',
    degree: 'MBA Finance',
    year: 2,
    semester: 3,
    skills: ['Financial Modeling', 'Valuation (DCF)', 'Advanced Excel', 'Tableau'],
    interests: ['Investment Banking', 'Fintech'],
    profile: { degree: 'MBA Finance', department: 'School of Management', cgpa: 9.2, batch: '2023-2025' },
  },
  {
    name: 'Karthik Subramanian',
    email: 'karthik.sub@student.in',
    role: 'student',
    primaryDomain: 'Management & Business',
    subField: 'Product Management',
    degree: 'MBA Tech',
    year: 2,
    semester: 4,
    skills: ['Product Lifecycle Management', 'Agile/Scrum', 'Wireframing', 'User Research'],
    interests: ['B2B SaaS', 'Growth Hacking'],
    profile: { degree: 'MBA Tech', department: 'Management', cgpa: 8.8, batch: '2023-2025' },
  },
  // 10% Healthcare & Ayush
  {
    name: 'Priya Nambiar',
    email: 'priya.nambiar@student.in',
    role: 'student',
    primaryDomain: 'Healthcare & Ayush',
    subField: 'Ayurveda & Traditional Medicine',
    degree: 'BAMS',
    year: 4,
    semester: 8,
    skills: ['Classical Diagnostic Principles (Ashtavidha)', 'Panchakarma Protocol Design', 'Good Clinical Practice (GCP)', 'Dravyaguna'],
    interests: ['Clinical Research', 'Pharmacovigilance'],
    profile: { degree: 'BAMS', department: 'Ayurvedic Medicine', cgpa: 9.0, batch: '2021-2025' },
  },
  // 10% Design & Arts
  {
    name: 'Tanvi Agarwal',
    email: 'tanvi.design@student.in',
    role: 'student',
    primaryDomain: 'Design & Creative Arts',
    subField: 'UI/UX & Product Design',
    degree: 'B.Des Product Design',
    year: 3,
    semester: 6,
    skills: ['Figma', 'Design Systems', 'User Research', 'Usability Testing', 'Prototyping'],
    interests: ['Design Systems', 'Mobile UX', 'Micro-interactions'],
    profile: { degree: 'B.Des', department: 'Design', cgpa: 9.3, batch: '2022-2026' },
  },
  // 10% Commerce & Finance
  {
    name: 'Harsh Vardhan',
    email: 'harsh.v@student.in',
    role: 'student',
    primaryDomain: 'Commerce & Finance',
    subField: 'Accounting & Audit',
    degree: 'M.Com Corporate Accounting',
    year: 2,
    semester: 3,
    skills: ['GST Filing & Compliance', 'Ind AS / IFRS', 'Tally Prime', 'Statutory Audit'],
    interests: ['Direct Taxation', 'Corporate Governance'],
    profile: { degree: 'M.Com', department: 'Commerce', cgpa: 8.5, batch: '2023-2025' },
  },
  // 10% Science & Research
  {
    name: 'Dr. Meera Iyer',
    email: 'meera.iyer@student.in',
    role: 'student',
    primaryDomain: 'Science & Research',
    subField: 'Applied Chemistry & Material Science',
    degree: 'M.Sc Organic Chemistry',
    year: 2,
    semester: 4,
    skills: ['Spectroscopy (NMR/IR/UV)', 'HPLC/GC-MS Analysis', 'Polymer Synthesis', 'Laboratory Quality Control'],
    interests: ['Green Chemistry', 'Nanomaterials'],
    profile: { degree: 'M.Sc Chemistry', department: 'Chemical Sciences', cgpa: 8.9, batch: '2023-2025' },
  },
];

export const additionalIndustries = [
  {
    name: 'Siddharth Varma (Apex Cloud)',
    email: 'siddharth@apexcloud.io',
    role: 'industry',
    primaryDomain: 'Engineering & Technology',
    profile: {
      companyName: 'Apex Cloud Systems Pvt. Ltd.',
      industrySector: 'Information Technology & Cloud Infrastructure',
      location: 'Bengaluru, Karnataka',
    },
  },
  {
    name: 'Nandini Sen (FinEdge Capital)',
    email: 'nandini@finedge.com',
    role: 'industry',
    primaryDomain: 'Management & Business',
    profile: {
      companyName: 'FinEdge Advisory & Ventures',
      industrySector: 'Banking & Financial Services',
      location: 'Mumbai, Maharashtra',
    },
  },
  {
    name: 'Dr. Devendra Joshi (AyurPharma Global)',
    email: 'devendra@ayurpharma.com',
    role: 'industry',
    primaryDomain: 'Healthcare & Ayush',
    profile: {
      companyName: 'AyurPharma Botanical Therapeutics Ltd.',
      industrySector: 'Ayush & Herbal Pharmaceuticals',
      location: 'Haridwar / New Delhi',
    },
  },
  {
    name: 'Pallavi Rao (Studio Aura)',
    email: 'pallavi@studioaura.design',
    role: 'industry',
    primaryDomain: 'Design & Creative Arts',
    profile: {
      companyName: 'Studio Aura Product Experience Lab',
      industrySector: 'Digital Media & Creative Industries',
      location: 'Pune, Maharashtra',
    },
  },
];

export const seedOpportunities = [
  // 40% Engineering (6 out of 15)
  {
    title: 'Full-Stack Cloud & Web Engineering Intern',
    companyName: 'NexGen Technologies & Cloud Solutions',
    type: 'internship',
    domain: 'Engineering & Technology',
    subField: 'Computer Science & IT',
    sector: 'Information Technology & Cloud Infrastructure',
    description: 'Join our core platform engineering pod building microservices, REST APIs, and scalable React UI components deployed on Kubernetes and GCP.',
    responsibilities: [
      'Design, test and deploy Node.js / Express microservices',
      'Craft responsive, accessible frontend features using React and Tailwind CSS',
      'Optimize database queries on PostgreSQL / MongoDB',
      'Participate in daily Agile scrums and CI/CD automated test reviews',
    ],
    requiredSkills: ['React', 'Node.js', 'SQL', 'Git', 'Docker'],
    location: 'Bengaluru (Hybrid)',
    workMode: 'hybrid',
    stipend: '₹35,000 / month',
    duration: '6 Months',
    positions: 4,
    eligibility: {
      degree: ['B.Tech', 'B.E.', 'MCA'],
      minCgpa: 7.5,
      allowedYears: [3, 4],
    },
    status: 'open',
  },
  {
    title: 'Machine Learning & Applied AI Engineer Intern',
    companyName: 'Apex Cloud Systems Pvt. Ltd.',
    type: 'internship',
    domain: 'Engineering & Technology',
    subField: 'Data Science & AI',
    sector: 'Artificial Intelligence & Analytics',
    description: 'Work alongside Senior Applied Scientists to train, fine-tune, and deploy transformer-based LLMs and predictive vision models on edge infrastructure.',
    responsibilities: [
      'Build feature engineering pipelines in Python and Pandas',
      'Evaluate model hallucination rates and accuracy benchmarks',
      'Deploy containerized inferencing endpoints via FastAPI and Triton Server',
    ],
    requiredSkills: ['Python', 'Machine Learning', 'TensorFlow', 'SQL'],
    location: 'Gurugram (On-site)',
    workMode: 'on-site',
    stipend: '₹40,000 / month',
    duration: '6 Months',
    positions: 2,
    eligibility: {
      degree: ['B.Tech', 'M.Tech', 'M.Sc Data Science'],
      minCgpa: 8.0,
      allowedYears: [3, 4],
    },
    status: 'open',
  },
  {
    title: 'Embedded Systems & IoT Firmware Developer',
    companyName: 'Voltaic Smart Grid Labs',
    type: 'internship',
    domain: 'Engineering & Technology',
    subField: 'Electronics & Communication',
    sector: 'Automobile & Electric Vehicles (EV)',
    description: 'Develop low-power telemetry firmware on STM32 microcontrollers communicating over MQTT and CAN bus for next-gen electric vehicle battery systems.',
    responsibilities: [
      'Write optimized Embedded C/C++ firmware modules',
      'Debug hardware timing issues using digital logic analyzers and oscilloscopes',
      'Implement secure OTA (Over-The-Air) firmware flashing routines',
    ],
    requiredSkills: ['Embedded C', 'IoT Protocols', 'RTOS', 'PCB Design'],
    location: 'Pune (On-site)',
    workMode: 'on-site',
    stipend: '₹30,000 / month',
    duration: '4 Months',
    positions: 3,
    eligibility: {
      degree: ['B.Tech ECE', 'B.Tech EEE', 'B.Tech Mechatronics'],
      minCgpa: 7.0,
      allowedYears: [3, 4],
    },
    status: 'open',
  },
  {
    title: 'Associate DevOps & Site Reliability Engineer',
    companyName: 'NexGen Technologies & Cloud Solutions',
    type: 'job',
    domain: 'Engineering & Technology',
    subField: 'Computer Science & IT',
    sector: 'Information Technology & Cloud Infrastructure',
    description: 'Accelerate enterprise deployments by engineering zero-downtime CI/CD pipelines, Terraform infrastructure-as-code, and automated Prometheus alerts.',
    responsibilities: [
      'Manage Kubernetes clusters on Google Cloud Platform',
      'Automate infrastructure provisioning using Terraform and Ansible',
      'Investigate production latency incidents and improve SLO compliance',
    ],
    requiredSkills: ['Docker', 'Kubernetes', 'Cloud/AWS', 'Linux Shell', 'Git'],
    location: 'Remote (Pan-India)',
    workMode: 'remote',
    stipend: '₹8.5 LPA',
    duration: 'Full-time',
    positions: 5,
    eligibility: {
      degree: ['B.Tech CSE', 'B.Tech IT', 'MCA'],
      minCgpa: 7.0,
      allowedYears: [4],
    },
    status: 'open',
  },
  {
    title: 'Automotive CAD & CAE Design Trainee',
    companyName: 'Kinetic Dynamic Motors',
    type: 'apprenticeship',
    domain: 'Engineering & Technology',
    subField: 'Mechanical & Automation',
    sector: 'Automobile & Electric Vehicles (EV)',
    description: 'Model chassis structures and perform finite element stress analyses (FEA) for lightweight composite electric two-wheelers.',
    responsibilities: [
      'Generate parametric 3D CAD models in SolidWorks',
      'Conduct structural crash simulation in ANSYS',
      'Prepare geometric dimensioning and tolerancing (GD&T) drawings',
    ],
    requiredSkills: ['CAD/SolidWorks', 'ANSYS', 'FEA Simulation', 'Geometric Dimensioning & Tolerancing (GD&T)'],
    location: 'Chennai (On-site)',
    workMode: 'on-site',
    stipend: '₹28,000 / month',
    duration: '1 Year',
    positions: 2,
    eligibility: {
      degree: ['B.Tech Mechanical', 'B.Tech Automobile'],
      minCgpa: 7.2,
      allowedYears: [4],
    },
    status: 'open',
  },
  {
    title: 'Bio-Process Engineering Research Associate',
    companyName: 'SynthoBio Technologies',
    type: 'project',
    domain: 'Engineering & Technology',
    subField: 'Biotechnology & Bio-Engineering',
    sector: 'Healthcare & Pharmaceuticals',
    description: 'Scale up microbial fermentation protocols and downstream chromatography purification for therapeutic enzymes and recombinant proteins.',
    responsibilities: [
      'Operate 50L bioreactors and track pH/dissolved oxygen kinetics',
      'Perform HPLC quantification of product yield and purity',
      'Maintain sterile cleanroom documentation according to cGMP standards',
    ],
    requiredSkills: ['HPLC', 'Bioreactor Operation', 'Fermentation Kinetics', 'Downstream Processing'],
    location: 'Hyderabad (On-site)',
    workMode: 'on-site',
    stipend: '₹32,000 / month',
    duration: '6 Months',
    positions: 2,
    eligibility: {
      degree: ['B.Tech Biotech', 'M.Sc Biotech', 'B.Pharm'],
      minCgpa: 7.5,
      allowedYears: [3, 4],
    },
    status: 'open',
  },

  // 20% Management (3 out of 15)
  {
    title: 'Associate Product Manager (APM) Intern',
    companyName: 'FinEdge Advisory & Ventures',
    type: 'internship',
    domain: 'Management & Business',
    subField: 'Product Management',
    sector: 'Banking & Financial Services',
    description: 'Translate customer problem spaces into crisp PRDs, define MVP scope, and collaborate directly with engineering teams in bi-weekly sprints.',
    responsibilities: [
      'Conduct qualitative customer discovery interviews and analyze funnel drop-offs',
      'Draft detailed product requirement documents (PRDs) and user stories in Jira',
      'Coordinate A/B testing experiments and track feature adoption metrics',
    ],
    requiredSkills: ['Product Lifecycle Management', 'Agile/Scrum', 'Figma', 'Data Analytics'],
    location: 'Bengaluru (Hybrid)',
    workMode: 'hybrid',
    stipend: '₹35,000 / month',
    duration: '6 Months',
    positions: 2,
    eligibility: {
      degree: ['MBA', 'B.Tech + MBA', 'BBA'],
      minCgpa: 7.5,
      allowedYears: [1, 2, 4],
    },
    status: 'open',
  },
  {
    title: 'Corporate Financial Analyst Trainee',
    companyName: 'FinEdge Advisory & Ventures',
    type: 'internship',
    domain: 'Management & Business',
    subField: 'Finance & Corporate Strategy',
    sector: 'Banking & Financial Services',
    description: 'Build three-statement financial models, analyze public comparables, and prepare investment committee pitch decks for Series A tech ventures.',
    responsibilities: [
      'Construct discounted cash flow (DCF) and LBO financial models',
      'Screen prospective target companies and synthesize industry market trends',
      'Perform working capital and burn-rate sensitivity simulations in Excel',
    ],
    requiredSkills: ['Financial Modeling', 'Valuation (DCF)', 'Advanced Excel', 'Financial Ratio Analysis'],
    location: 'Mumbai (On-site)',
    workMode: 'on-site',
    stipend: '₹38,000 / month',
    duration: '6 Months',
    positions: 3,
    eligibility: {
      degree: ['MBA Finance', 'CA Inter', 'CFA Candidate', 'B.Com Hons'],
      minCgpa: 8.0,
      allowedYears: [1, 2],
    },
    status: 'open',
  },
  {
    title: 'Global Supply Chain & Operations Associate',
    companyName: 'Apex Cloud Systems Pvt. Ltd.',
    type: 'job',
    domain: 'Management & Business',
    subField: 'Operations & Supply Chain',
    sector: 'Consumer Goods & FMCG',
    description: 'Lead inventory demand forecasting, vendor SLA audits, and cross-border logistics tracking to minimize warehouse dwell time.',
    responsibilities: [
      'Utilize ERP/SAP modules to synchronize supply-demand allocation',
      'Apply Lean Six Sigma methodologies to eliminate shipping dispatch bottlenecks',
      'Analyze freight carrier performance dashboards and negotiate bulk rates',
    ],
    requiredSkills: ['Supply Chain Optimization', 'Six Sigma / Lean', 'ERP/SAP', 'Inventory Forecasting'],
    location: 'Gurugram (Hybrid)',
    workMode: 'hybrid',
    stipend: '₹7.2 LPA',
    duration: 'Full-time',
    positions: 2,
    eligibility: {
      degree: ['MBA Operations', 'B.Tech Industrial Engineering'],
      minCgpa: 7.2,
      allowedYears: [4],
    },
    status: 'open',
  },

  // 10% Healthcare & Ayush (2 out of 15)
  {
    title: 'Ayush Clinical Trials & Pharmacovigilance Associate',
    companyName: 'AyurPharma Botanical Therapeutics Ltd.',
    type: 'internship',
    domain: 'Healthcare & Ayush',
    subField: 'Clinical Research & Trials',
    sector: 'Ayush & Herbal Pharmaceuticals',
    description: 'Assist principal investigators in patient screening, informed consent administration, and Adverse Event reporting for double-blind phytomedicine trials.',
    responsibilities: [
      'Audit clinical trial Case Report Forms (eCRF) for regulatory compliance',
      'Monitor patient vitals, adverse event logs, and therapeutic adherence',
      'Coordinate with Central Institutional Ethics Committees for protocol updates',
    ],
    requiredSkills: ['Good Clinical Practice (GCP)', 'Pharmacovigilance Reporting', 'Clinical Research Protocol Design', 'eCRF Management'],
    location: 'New Delhi / AIIA Clinical Wing',
    workMode: 'on-site',
    stipend: '₹32,000 / month',
    duration: '6 Months',
    positions: 3,
    eligibility: {
      degree: ['BAMS', 'MD (Ayu)', 'B.Pharm', 'M.Sc Clinical Research'],
      minCgpa: 7.5,
      allowedYears: [4, 5],
    },
    status: 'open',
  },
  {
    title: 'Ayurvedic Drug Standardization & QC Analyst',
    companyName: 'AyurPharma Botanical Therapeutics Ltd.',
    type: 'internship',
    domain: 'Healthcare & Ayush',
    subField: 'Pharmaceutical Sciences & Regulatory',
    sector: 'Ayush & Herbal Pharmaceuticals',
    description: 'Standardize classical herbal extracts using HPTLC fingerprinting, heavy metal ICP-MS testing, and microbial load estimation under Schedule T GMP.',
    responsibilities: [
      'Extract bioactive markers (Curcuminoids, Withanolides) from raw botanical samples',
      'Perform moisture, ash value, and solvent extractive assays per Ayurvedic Pharmacopoeia of India (API)',
      'Prepare Certificate of Analysis (CoA) batches for export shipments',
    ],
    requiredSkills: ['Good Manufacturing Practices (GMP)', 'Herbal Standardization', 'HPTLC', 'Pharmacopoeial Testing'],
    location: 'Haridwar (On-site)',
    workMode: 'on-site',
    stipend: '₹28,000 / month',
    duration: '6 Months',
    positions: 2,
    eligibility: {
      degree: ['BAMS', 'B.Pharm (Ayurveda)', 'M.Sc Botany', 'M.Pharm'],
      minCgpa: 7.0,
      allowedYears: [3, 4],
    },
    status: 'open',
  },

  // 10% Design & Creative Arts (2 out of 15)
  {
    title: 'UI/UX & Design Systems Intern',
    companyName: 'Studio Aura Product Experience Lab',
    type: 'internship',
    domain: 'Design & Creative Arts',
    subField: 'UI/UX & Product Design',
    sector: 'Digital Media & Creative Industries',
    description: 'Design production-grade tokenized component libraries in Figma and collaborate with frontend engineers on micro-interactions and motion accessibility.',
    responsibilities: [
      'Construct scalable Auto Layout components conforming to WCAG AA contrast standards',
      'Conduct remote usability testing sessions and map heatmaps',
      'Produce interactive prototypes with variable states in Figma',
    ],
    requiredSkills: ['Figma', 'Design Systems', 'User Research', 'Usability Testing'],
    location: 'Bengaluru (Remote)',
    workMode: 'remote',
    stipend: '₹30,000 / month',
    duration: '4 Months',
    positions: 2,
    eligibility: {
      degree: ['B.Des', 'M.Des', 'B.Tech with Design Portfolio'],
      minCgpa: 7.0,
      allowedYears: [2, 3, 4],
    },
    status: 'open',
  },
  {
    title: '3D Motion Graphics & Visual Brand Specialist',
    companyName: 'Studio Aura Product Experience Lab',
    type: 'internship',
    domain: 'Design & Creative Arts',
    subField: 'Animation & Game Design',
    sector: 'Digital Media & Creative Industries',
    description: 'Create high-fidelity product renders, explainer videos, and real-time 3D assets for product launches and interactive web experiences.',
    responsibilities: [
      'Render 3D lighting scenes in Blender / Cinema 4D',
      'Animate vector keyframes and kinetic typography in Adobe After Effects',
      'Optimize glTF assets for three.js web viewports',
    ],
    requiredSkills: ['Blender/3D Modeling', 'After Effects', 'Design Systems'],
    location: 'Mumbai (Hybrid)',
    workMode: 'hybrid',
    stipend: '₹26,000 / month',
    duration: '3 Months',
    positions: 2,
    eligibility: {
      degree: ['B.Des', 'Diploma in Animation', 'B.Sc Multimedia'],
      minCgpa: 6.5,
      allowedYears: [2, 3, 4],
    },
    status: 'open',
  },

  // 10% Commerce & Finance / Agriculture / Science (2 out of 15)
  {
    title: 'Fintech API Integration & Payments Intern',
    companyName: 'FinEdge Advisory & Ventures',
    type: 'internship',
    domain: 'Commerce & Finance',
    subField: 'Banking & Fintech',
    sector: 'Banking & Financial Services',
    description: 'Integrate UPI, payment gateways, and automated reconciliation ledgers for merchant banking micro-apps.',
    responsibilities: [
      'Integrate webhook notification handlers for instant payment settlements',
      'Ensure zero discrepancy between payment gateway logs and core ledger balances',
      'Write automated integration tests for settlement failure recoveries',
    ],
    requiredSkills: ['Fintech APIs & Payments', 'GST Filing & Compliance', 'SQL', 'Postman'],
    location: 'Gurugram (Hybrid)',
    workMode: 'hybrid',
    stipend: '₹32,000 / month',
    duration: '6 Months',
    positions: 2,
    eligibility: {
      degree: ['B.Com + Tech', 'B.Tech CS', 'M.Com Fintech'],
      minCgpa: 7.5,
      allowedYears: [3, 4],
    },
    status: 'open',
  },
  {
    title: 'Precision Agriculture IoT & Soil Sensing Apprentice',
    companyName: 'AgriNova Sensor Systems',
    type: 'internship',
    domain: 'Agriculture & Allied Sciences',
    subField: 'Precision Agriculture & Crop Science',
    sector: 'Agriculture & Food Processing',
    description: 'Deploy LoRaWAN soil moisture and NPK sensor arrays across pilot test farms, connecting data to automated drip irrigation controllers.',
    responsibilities: [
      'Calibrate electrochemical soil sensors and solar battery backup modules',
      'Map satellite NDVI vegetative indices against ground sensor readings',
      'Present seasonal crop yield reports to agronomist supervisors',
    ],
    requiredSkills: ['Precision Farming Tools', 'IoT Protocols', 'GIS Mapping', 'Data Analysis'],
    location: 'Nagpur (On-site)',
    workMode: 'on-site',
    stipend: '₹25,000 / month',
    duration: '6 Months',
    positions: 3,
    eligibility: {
      degree: ['B.Sc Agriculture', 'B.Tech Agricultural Engg', 'B.Tech ECE'],
      minCgpa: 7.0,
      allowedYears: [3, 4],
    },
    status: 'open',
  },
];

export const seedLearningPrograms = [
  {
    title: 'Enterprise Microservices & Cloud-Native Architecture',
    providerName: 'NexGen Technologies & Cloud Solutions',
    domain: 'Engineering & Technology',
    subField: 'Computer Science & IT',
    sector: 'Information Technology & Cloud Infrastructure',
    description: 'Hands-on industry curriculum covering Docker containerization, Kubernetes orchestration, gRPC services, and event-driven architectures with Kafka.',
    skillsCovered: ['Node.js', 'Docker', 'Kubernetes', 'Cloud/AWS', 'System Design'],
    durationWeeks: 8,
    mode: 'online',
    isCertified: true,
    certificateTitle: 'Certified Cloud-Native Microservices Specialist',
    syllabus: [
      { week: 1, topic: 'Container Fundamentals & Multi-Stage Docker Builds' },
      { week: 2, topic: 'Kubernetes Pods, Services, and Ingress Routing' },
      { week: 3, topic: 'Asynchronous Messaging with Kafka and RabbitMQ' },
      { week: 4, topic: 'Production Observability: Prometheus and OpenTelemetry' },
    ],
    enrolledCount: 142,
  },
  {
    title: 'Advanced Applied AI & LLM Fine-Tuning Bootcamp',
    providerName: 'Apex Cloud Systems Pvt. Ltd.',
    domain: 'Engineering & Technology',
    subField: 'Data Science & AI',
    sector: 'Artificial Intelligence & Analytics',
    description: 'Master practical parameter-efficient fine-tuning (LoRA), RAG architectures with vector embeddings, and LangChain orchestration.',
    skillsCovered: ['Python', 'Machine Learning', 'Deep Learning', 'SQL'],
    durationWeeks: 10,
    mode: 'online',
    isCertified: true,
    certificateTitle: 'Applied Generative AI Practitioner Credential',
    syllabus: [
      { week: 1, topic: 'Vector Embeddings and Semantic Search Architectures' },
      { week: 2, topic: 'Retrieval Augmented Generation (RAG) with ChromaDB' },
      { week: 3, topic: 'Quantization and Local Model Inference with Ollama' },
    ],
    enrolledCount: 198,
  },
  {
    title: 'Financial Modeling & Venture Valuation Masterclass',
    providerName: 'FinEdge Advisory & Ventures',
    domain: 'Management & Business',
    subField: 'Finance & Corporate Strategy',
    sector: 'Banking & Financial Services',
    description: 'Learn real-world Wall Street financial modeling techniques: 3-statement models, DCF valuation, sensitivity tables, and capital structuring.',
    skillsCovered: ['Financial Modeling', 'Valuation (DCF)', 'Advanced Excel'],
    durationWeeks: 6,
    mode: 'online',
    isCertified: true,
    certificateTitle: 'Certified Financial Modeling & Valuation Analyst',
    syllabus: [
      { week: 1, topic: 'Building Integrated 3-Statement Financial Models' },
      { week: 2, topic: 'Cost of Capital (WACC) & Unlevered Free Cash Flows' },
      { week: 3, topic: 'Scenario Planning & Dynamic Sensitivity Analysis' },
    ],
    enrolledCount: 86,
  },
  {
    title: 'Design Systems & Enterprise Product Design',
    providerName: 'Studio Aura Product Experience Lab',
    domain: 'Design & Creative Arts',
    subField: 'UI/UX & Product Design',
    sector: 'Digital Media & Creative Industries',
    description: 'Architect atomic design systems in Figma with variables, tokenized themes, accessibility auditing, and seamless developer handoff.',
    skillsCovered: ['Figma', 'Design Systems', 'User Research', 'Usability Testing'],
    durationWeeks: 6,
    mode: 'hybrid',
    isCertified: true,
    certificateTitle: 'Enterprise Design Systems Specialist',
    syllabus: [
      { week: 1, topic: 'Design Tokens, Variables & Color Systems' },
      { week: 2, topic: 'Component Componentization & Nested Auto Layout' },
      { week: 3, topic: 'WCAG 2.2 AA Contrast & Accessibility Compliance' },
    ],
    enrolledCount: 110,
  },
  {
    title: 'ICH-GCP Clinical Trial Operations & Protocol Management',
    providerName: 'AyurPharma Botanical Therapeutics Ltd.',
    domain: 'Healthcare & Ayush',
    subField: 'Clinical Research & Trials',
    sector: 'Healthcare & Pharmaceuticals',
    description: 'Comprehensive certification in Good Clinical Practice, ethics submissions, SAE reporting, and electronic Case Report Form auditing.',
    skillsCovered: ['Good Clinical Practice (GCP)', 'Pharmacovigilance Reporting', 'Clinical Research Protocol Design'],
    durationWeeks: 8,
    mode: 'online',
    isCertified: true,
    certificateTitle: 'Certified Ayush Clinical Trial Coordinator',
    syllabus: [
      { week: 1, topic: 'ICH-GCP E6 (R2) Principles and Legal Framework' },
      { week: 2, topic: 'Informed Consent Process and Ethical Governance' },
      { week: 3, topic: 'Pharmacovigilance and Serious Adverse Event Reporting' },
    ],
    enrolledCount: 75,
  },
];

export const seedFacultyOpportunities = [
  {
    title: 'Industry Research Fellowship: Distributed Edge Systems',
    companyName: 'NexGen Technologies & Cloud Solutions',
    type: 'research-fellowship',
    stipend: '₹75,000 / month honorarium',
    duration: '1 Year',
    requiredExpertise: ['Distributed Systems', 'Cloud Architecture', 'Container Orchestration'],
    deliverables: ['Peer-reviewed publication', 'Prototype microservice benchmark'],
  },
  {
    title: 'Visiting Corporate Faculty: Corporate Valuation & FinTech',
    companyName: 'FinEdge Advisory & Ventures',
    type: 'corporate-mentorship',
    stipend: 'Honorarium per executive workshop',
    duration: 'Semester long',
    requiredExpertise: ['Corporate Valuation', 'FinTech Regulation', 'Capital Markets'],
    deliverables: ['Executive curriculum review', 'Case study authoring'],
  },
];

export const seedCollabEvents = [
  {
    title: 'National Cross-Disciplinary Innovation Hackathon 2026',
    theme: 'Smart Automation & Sustainable Industry Systems',
    type: 'hackathon',
    eventDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    registrationDeadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    prizePool: '₹5,00,000 + Incubation Support',
  },
  {
    title: 'Academia-Industry Convergence Summit on Digital Health',
    theme: 'Digital Therapeutics, ABDM Standards & Herbal Drug Modernization',
    type: 'conference',
    eventDate: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
    registrationDeadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
    prizePool: 'Best Paper Grants & Industry MoUs',
  },
];
